
test:
  adapter: postgresql
  database: recipes
  host: localhost


development:
  adapter: postgresql
  database: recipes
  host: localhost


production:
  adapter: postgresql
  database: recipes
  host: localhost